### ISSUE TITLE
XBE

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/ncov-recombinant#177]
[pango designation issue #1246](https://github.com/cov-lineages/pango-designation/issues/1246)

## Parents

**Clade**: `Omicron/BA.5.2`,`Omicron/BA.5.3`
**Lineage**: `BA.5.2*`,`BA.5.2.1*`
**Lineage Confidence**: `0.977`,`0.328`

## Alleles

![image](https://user-images.githubusercontent.com/14981272/197900581-affe26ba-d063-491e-b409-d10bd9ec27bf.png)

## Breakpoints

**Breakpoint 1**: `16936:27037`

## Tasks

- [x] `resources/breakpoints.tsv` Updated

**Comment by ktmeaton** [comment]
The full plot (all lineages) looks horrible!

Alternate view, where legend is placed on top:

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198104452-f753bf6f-2bae-41bd-8bfe-74c18e5a8e8d.png)

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198104534-610b2248-4c46-45b0-8f23-36389f155506.png)

With added special sizing for large numbers of lineages:

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198105758-670e71e9-b12f-4d8d-9269-358b73b69fb6.png)

**Comment by ktmeaton** [comment]
Public `controls` are looking good!

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198107283-495103a0-0ac0-42da-8eaf-4c40c5814348.png)

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198107372-2f209521-5f7f-4c16-96ea-3fc38f51c8be.png)

**Comment by ktmeaton** [comment]
`controls-gisaid` looking excellent as well.

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198108060-1ac70ca9-d498-4cf6-8dfe-2111f4189a65.png)

![breakpoints_clade](https://user-images.githubusercontent.com/14981272/198108093-270dec45-16c8-4550-8fe4-e81ae44f479d.png)

**Comment by FedeGueli** [comment]
Wonderful work.
